### ISSUE TITLE
How can I fix this problem

### ISSUE THREAD

**Issue by fjqdxq** [GenaroNetwork/GenaroCore#1]
when I make go-genaro, it's ok, but when I make all, I have the following problem:

cmd/swarm/db.go:28:2: cannot find package "github.com/mkideal/cli" in any of:
	/home/genaro/GenaroCore/build/_workspace/src/github.com/GenaroNetwork/GenaroCore/vendor/github.com/mkideal/cli (vendor tree)
	/usr/local/go/src/github.com/mkideal/cli (from $GOROOT)
	/home/genaro/GenaroCore/build/_workspace/src/github.com/mkideal/cli (from $GOPATH)

thanks!

**Comment by G-zhanghao** [comment]
This line is useless, you can delete it.

**Comment by G-zhanghao** [comment]
New submission has been pushed.
